"""PDF parsing (input) + PDF generation (output) helpers."""
from __future__ import annotations

import io
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def extract_text_from_pdf(file_bytes: bytes) -> str:
    """Extract text from an uploaded PDF using pdfplumber, fallback to pypdf."""
    try:
        import pdfplumber

        text_parts: list[str] = []
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            for page in pdf.pages:
                t = page.extract_text() or ""
                text_parts.append(t)
        text = "\n\n".join(text_parts).strip()
        if text:
            return text
    except Exception as exc:
        logger.warning("pdfplumber failed: %s — falling back to pypdf.", exc)

    from pypdf import PdfReader

    reader = PdfReader(io.BytesIO(file_bytes))
    parts = [page.extract_text() or "" for page in reader.pages]
    return "\n\n".join(parts).strip()


def text_to_docx(title: str, body: str) -> bytes:
    """Render plain text to a styled Word .docx — editable in MS Word/LibreOffice."""
    from docx import Document
    from docx.shared import Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin = Cm(2)
        section.right_margin = Cm(2)

    # Default body style
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # Title
    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = t.add_run(title)
    run.bold = True
    run.font.size = Pt(18)
    run.font.color.rgb = RGBColor(0x0A, 0x0A, 0x0B)

    # Sub
    s = doc.add_paragraph()
    s.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub = s.add_run("Generated by Smart Court")
    sub.italic = True
    sub.font.size = Pt(10)
    sub.font.color.rgb = RGBColor(0x05, 0x96, 0x69)

    doc.add_paragraph("")  # spacer

    # Body — split into paragraphs on blank lines
    for block in (body or "").split("\n\n"):
        para = doc.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        for i, line in enumerate(block.split("\n")):
            if i > 0:
                para.add_run().add_break()
            para.add_run(line)

    doc.add_paragraph("")
    sig = doc.add_paragraph("_______________________")
    sig.alignment = WD_ALIGN_PARAGRAPH.LEFT
    sigl = doc.add_paragraph("Signature & CNIC")
    sigl.runs[0].font.size = Pt(10)
    sigl.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    import io
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def text_to_pdf(title: str, body: str) -> bytes:
    """Render a plain-text legal document to a stamped-paper-style PDF."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        HRFlowable,
    )
    from reportlab.lib.colors import HexColor

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=title,
        author="Smart Court",
    )

    base = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        alignment=TA_CENTER,
        textColor=HexColor("#0A0F1E"),
        spaceAfter=10,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=base["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=10,
        alignment=TA_CENTER,
        textColor=HexColor("#C9A84C"),
        spaceAfter=18,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=10,
    )

    flow = [
        Paragraph(title, title_style),
        Paragraph("Generated by Smart Court — Pakistan's AI Legal Co-Pilot", subtitle_style),
        HRFlowable(width="100%", color=HexColor("#C9A84C"), thickness=1, spaceAfter=14),
    ]

    for block in body.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        safe = (block.replace("&", "&amp;")
                     .replace("<", "&lt;")
                     .replace(">", "&gt;")
                     .replace("\n", "<br/>"))
        flow.append(Paragraph(safe, body_style))
        flow.append(Spacer(1, 4))

    flow.append(Spacer(1, 24))
    flow.append(HRFlowable(width="40%", color=HexColor("#0A0F1E"), thickness=0.5))
    flow.append(Paragraph("Signature & CNIC", body_style))

    doc.build(flow)
    return buf.getvalue()
